export const LOGIN_USER_SUCCESSFUL = 'LOGIN_USER_SUCCESSFUL';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESSFUL = 'REGISTER_USER_SUCCESSFUL';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const RESET_PASSWORD_SUCCESSFUL = 'RESET_PASSWORD_SUCCESSFUL';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const PROFILE_INFORMATION_UPDATED = 'PROFILE_INFORMATION_UPDATED';

export const PERSONAL_INFORMATION_UPDATE_SUCCESSFUL = 'PERSONAL_INFORMATION_UPDATE_SUCCESSFUL';
export const EMPLOYMENT_INFORMATION_UPDATE_SUCCESSFUL = 'EMPLOYMENT_INFORMATION_UPDATE_SUCCESSFUL';
export const CONTACT_PERSON_INFORMATION_UPDATE_SUCCESSFUL = 'CONTACT_PERSON_INFORMATION_UPDATE_SUCCESSFUL';
export const SALARY_INFORMATION_UPDATE_SUCCESSFUL = 'SALARY_INFORMATION_UPDATE_SUCCESSFUL';

export const GET_CART_SUCCESSFUL = 'GET_CART_SUCCESSFUL';
export const GET_CART_FAILED = 'GET_CART_FAILED';

export const DELETE_CART_SUCCESSFUL ='DELETE_CART_SUCCESSFUL';
export const DELETE_CART_FAILED = 'DELETE_CART_FAILED';

export const RESPONSE_SUCCESS_MESSAGE = 'RESPONSE_SUCCESS_MESSAGE';
export const RESPONSE_ERROR_MESSAGE = 'RESPONSE_ERROR_MESSAGE'; 
export const RESPONSE_REMOVE_MESSAGE = 'RESPONSE_REMOVE_MESSAGE';

export const UNCHECKED_FINANCING = 'UNCHECKED_FINANCING';
export const CHECKED_FINANCING = 'CHECKED_FINANCING';

export const FINANCING_INFORMATION_UPDATED = 'FINANCING_INFORMATION_UPDATED';